modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TehNut/Harvest/issues"
displayURL="https://github.com/TehNut/Harvest"
authors="TehNut"
[[mods]]
    modId="harvest"
    version="${version}"
    displayName="Harvest"
    description="Right click crop harvesting"
[[dependencies.waila]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waila]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"